<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="referencearchitecturemodeling" nsURI="http://it.univaq.disim/referencearchitecturemodeling-1st-revision"
    nsPrefix="referencearchitecturemodeling">
  <eClassifiers xsi:type="ecore:EClass" name="ReferenceArchitecturalModel">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="referenceArchitecturalName"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="raelements" lowerBound="1"
        upperBound="-1" eType="#//RAElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="raattributes" upperBound="-1"
        eType="#//RAAttribute" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RAElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="#//RAAttribute"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="highlighted" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="types" upperBound="-1"
        eType="#//RAElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RAComponent" eSuperTypes="#//RAElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="child" upperBound="-1"
        eType="#//RAElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incoming" upperBound="-1"
        eType="#//RAConnector" eOpposite="#//RAConnector/targetRef"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoing" upperBound="-1"
        eType="#//RAConnector" eOpposite="#//RAConnector/sourceRef"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mandatory" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RAConnector" eSuperTypes="#//RAElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetRef" lowerBound="1"
        eType="#//RAComponent" eOpposite="#//RAComponent/incoming"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceRef" lowerBound="1"
        eType="#//RAComponent" eOpposite="#//RAComponent/outgoing"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="twoWay" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RAAttribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//RAValueType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RAValueType" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RASimpleValueType" abstract="true" eSuperTypes="#//RAValueType"/>
  <eClassifiers xsi:type="ecore:EClass" name="RAComplexValueType" eSuperTypes="#//RAValueType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="child" lowerBound="1" upperBound="-1"
        eType="#//RAValueType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RAEnumerationValueType" eSuperTypes="#//RAValueType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" lowerBound="1"
        upperBound="-1" eType="#//RAEnumerationItem" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1" eType="#//RAEnumerationItem"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RAEnumerationItem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RATextValueType" eSuperTypes="#//RASimpleValueType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RAIntegerValueType" eSuperTypes="#//RASimpleValueType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RARealValueType" eSuperTypes="#//RASimpleValueType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RABooleanValueType" eSuperTypes="#//RASimpleValueType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
  </eClassifiers>
</ecore:EPackage>
