<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="RAPublisherSubscriber" nsURI="http://it.univaq.disim/RAPublisherSubscriber"
    nsPrefix="RAPublisherSubscriber">
  <eClassifiers xsi:type="ecore:EClass" name="Publisher">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="protocol" eType="#//ProtocolEnum"
        defaultValueLiteral="MQTT"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Subscriber">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="protocol" eType="#//ProtocolEnum"
        defaultValueLiteral="MQTT"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Broker">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="protocol" eType="#//ProtocolEnum"
        defaultValueLiteral="MQTT"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ProtocolEnum">
    <eLiterals name="MQTT"/>
    <eLiterals name="XMPP" value="1"/>
    <eLiterals name="AMQP" value="2"/>
    <eLiterals name="CoAP" value="3"/>
    <eLiterals name="DDS" value="4"/>
    <eLiterals name="MQTT_over_WSS" value="5"/>
    <eLiterals name="LoRaWAN" value="6"/>
    <eLiterals name="Https" value="7"/>
  </eClassifiers>
</ecore:EPackage>
